function [neutAxis,t]=NeuturalAxis(N,b,E,Layer)
%Calculate the neutral axis position
neutAxis= (E(1)*b(1)*Layer(2)*Layer(2)/2+...
    E(2)*b(2)*Layer(3)*(Layer(2)+Layer(3)/2)+...
    E(3)*b(3)*Layer(4)*(Layer(2)+Layer(3)+Layer(4)/2)+...
    E(4)*b(4)*Layer(5)*(Layer(2)+Layer(3)+Layer(4)+Layer(5)/2))...
    /(E(1)*b(1)*Layer(2)+E(2)*b(2)*Layer(3)+E(3)*b(3)*Layer(4)+E(4)*b(4)*Layer(5));
%Calculate the distance of each layer from the neutral axis
t(1)=-neutAxis+Layer(1); t(2)=-neutAxis+Layer(2);
for rr=3:N
    t(rr)=t(rr-1)+Layer(rr);
end